encyclopedia/urls.py
from django.urls import path

from . import views

app_name = "entry"

urlpatterns = [
    path("", views.index, name="index"), 
    path("wiki/<str:entry>", views.wiki, name="wiki"),
    path("search", views.search, name="search"),
    path("new_page", views.new_page, name="new_page"),
    path("edit/<str:entry>", views.edit, name="edit"),
    path("caso", views.caso, name="caso")
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
import markdown2
import random

from . import util


def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

# To display an entry page
def wiki(request, entry):
    # Get the list of all entries
    entry_list = util.list_entries()
    # Lower case the list to compare with entry, case-insensetive
    entry_list = [x.lower() for x in entry_list]
    # The entry exists
    if entry.lower() in entry_list: 
        text = markdown2.markdown(util.get_entry(entry))
        title = util.get_entry(entry)
        return render(request, "encyclopedia/wiki.html", {
            "entry": entry,
            "text": text, 
            "list": entry_list
        })
    # The entry doesn't exists
    else:
        # We have to change here to redirect to customise error page
        return render(request, "encyclopedia/not_found.html", {
            "entry": entry
        })
    
# Search function
def search(request):
    if request.method == "POST":
        entry = request.POST["q"]
        # Convert all the entries in uppercase 
        list = util.list_entries()
        list = [x.upper() for x in list]
        # Is in the list
        if entry.upper() in list:
            return HttpResponseRedirect(reverse("entry:wiki", args=(entry, )))
        # Isn't in the list
        else:
            substring = [i for i in list if entry.upper() in i]
            return render(request, "encyclopedia/search.html", {
                "substring": substring
            })
        
        
# Create a new page
def new_page(request):
    # user submit the page
    if request.method == "POST":
        title = request.POST["title"]
        text = request.POST["text"]
        # Check user submit empty field
        if title == "" or text == "":
            return render (request, "encyclopedia/new_page.html", {
                "message" : "Can't save with an empty field"
            })
        # Check if the entry already exists
        entry_list = util.list_entries()
        # Ignoring upper and lowercase
        entry_list = [x.lower() for x in entry_list]
        if title.lower() in entry_list:
            return render(request, "encyclopedia/new_page.html", {
                "message": "This entry already exists"
            })
        # User submit valid input
        else: 
            util.save_entry(title, text)
            return HttpResponseRedirect(reverse("entry:wiki", args=(title, )))
    # user get the page
    else:
        return render(request, "encyclopedia/new_page.html")
    
# Edit page
def edit(request, entry):
    text = util.get_entry(entry)
    if request.method == "POST":
        title = request.POST["title"]
        text = request.POST["content"]
        # User submit an empty input
        if title == "" or text == "":
            return render(request, "encyclopedia/edit.html", {
                "message" : "Can't save with an empty field", 
                "title" : entry, 
                "text" : text
            })
        entry_list = util.list_entries()
        entry_list = [x.lower() for x in entry_list]
        util.save_entry(title, text)
        return HttpResponseRedirect(reverse("entry:wiki", args=(title, )))
    else:
        return render(request, "encyclopedia/edit.html", {
            "title": entry, 
            "text": text
        })
        
# Random search
def caso(request):
    list = util.list_entries()
    entry = random.choice(list)
    return HttpResponseRedirect(reverse("entry:wiki", args=(entry, )))

encyclopedia/templates/encyclopedia/caso.html
Random

<div>
LIST: {{ entry }}
</div>

encyclopedia/templates/encyclopedia/edit.html
{% extends 'encyclopedia/layout.html' %}

{% block body %}
<h2>Edit page: {{ title }}</h2>
{% if message %}
<div>
    {{ message }}
</div>
{% endif %}
<div class="container">
    <form action="{% url 'entry:edit' title %}" method="post">
        {% csrf_token %}
        <div class="container">
            <label for="title">Title</label>
            <input class="form-control-md" type="text"  required name="title" placeholder="Title" value="{{ title }}">
        </div>
        <div class="container" style="margin:20px;">
            <p>Content</p>
            <textarea style="height: 200px;" name="content" required placeholder="Markdown syntax">{{ text | safe }}</textarea>
        </div>
        <div>
            <input class="btn btn-light" style="margin: 10px;" type="submit">
        </div>
    </form>
</div>
{% endblock %}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}
    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
             <li>
                <a href="{% url 'entry:wiki' entry=entry %}">{{ entry }}</a>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form method="post" action="{% url 'entry:search' %}">
                    {% csrf_token %}
                    <input class="search" type="text" name="q" placeholder="Search Encyclopedia">
                </form>
                <div style="margin: 10px 10px 10px 0px;">
                    <a href="{% url 'entry:index' %}">Home</a>
                </div>
                <div style="margin: 10px 10px 10px 0px;">
                    <a href="{% url 'entry:new_page' %}">Create New Page</a>
                </div>
                <div style="margin: 10px 10px 10px 0px;">
                    <a href="{% url 'entry:caso' %}">Random Page</a> 
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/new_page.html
{% extends "encyclopedia/layout.html" %}

{% block title %}New Page{% endblock %}

{% block body %}

<h1>New page</h1>
{% if message %}
{{ message }}
{% endif %}

<div class="container">
    <form action="{% url 'entry:new_page' %}" method="post">
        {% csrf_token %}
        <div class="container">
            <label for="title">Title</label>
            <input class="form-control-md" type="text"  required name="title">
        </div>
        <div class="container" style="margin: 20px;">
            <label for="text">Content</label>
            <textarea style="height: 200px;"  class="form-control" name="text" required placeholder="Markdown syntax"></textarea>
        </div>
        <div>
            <input class="btn btn-light" style="margin: 10px;" type="submit" value="Create" >
        </div>
    </form>
</div>
<div class="container" style="margin: 20px;">
    <p>Discover more about markdown syntax at <a href="https://www.markdownguide.org/basic-syntax/">Markdwon syntax</a></p>
</div>

{% endblock %}

encyclopedia/templates/encyclopedia/not_found.html
{% extends 'encyclopedia/layout.html' %}

{% block body %}
    <h1>Not found</h1>
    <p>The entry <i>"{{ entry }}"</i> doesn't exists</p>
{% endblock %}

encyclopedia/templates/encyclopedia/search.html
{% extends 'encyclopedia/layout.html' %}

{% block body %}
<h1>Results</h1>
<div>
    <ul>
        {% if substring %}
            {% for entry in substring %}
                <li>
                    <a href="{% url 'entry:wiki' entry=entry %}">{{ entry }}</a>
                </li>
            {% endfor %}
    </ul>
        {% else %}
                <p>No results for this query</p>
        {% endif %}
</div>

{% endblock %}

encyclopedia/templates/encyclopedia/wiki.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}{{ entry }}{% endblock %}

{% block body %}
<div>
    {{ text | safe}}
</div>

<form name="entry" action="{% url 'entry:edit' entry %}">
    <input type="submit" value="Edit">
</form>
{% endblock %}

encyclopedia/templates/encyclopedia/wiky.html
{% extends 'encyclopedia/layout.html' %}

{% block title %}{{ entry }}{% endblock %}

{% block body %}
<div>
    {{ text | safe}}
</div>

<form name="entry" action="{% url 'entry:edit' entry %}">
    <input type="submit" value="Edit">
</form>
{% endblock %}